#ifndef SERVO_CONFIG_H_
#define SERVO_CONFIG_H_


/*TRIG PIN CONFIG*/
#define TRIG_PORT   MGPIOA_PERIPHERAL
#define TRIG_PIN    MGPIO_PIN9


/*ECHO PIN CONFIG*/
#define ECHO_PORT   MGPIOA_PERIPHERAL
#define ECHO_PIN    MGPIO_PIN10


#endif
